name: 'Zigbee Humidity Sensor (nereusuj)'
packageKey: 'zigbee-humidity-sensor-nereusuj'
permissions:
  zigbee: {}
description: 'Zigbee Humidity Sensor Driver with dashboard patched by NereusUJ'
vendorSupportInformation: "https://github.com/nereusuj/ST-Edge-Drivers"
